// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD774wFTpieob0opuKh0MpB28G2XJGPXsA',
    appId: '1:582817729094:android:3260d052376f9edba05847',
    messagingSenderId: '582817729094',
    projectId: 'dental-clinic-9cbf2',
    databaseURL: 'https://dental-clinic-9cbf2-default-rtdb.firebaseio.com',
    storageBucket: 'dental-clinic-9cbf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtZ8w-MccaP21zeNAXPOHGDacCbj7EKjA',
    appId: '1:582817729094:ios:f06a3dba576f2016a05847',
    messagingSenderId: '582817729094',
    projectId: 'dental-clinic-9cbf2',
    databaseURL: 'https://dental-clinic-9cbf2-default-rtdb.firebaseio.com',
    storageBucket: 'dental-clinic-9cbf2.appspot.com',
    iosBundleId: 'com.example.dentalClinicMobile',
  );
}
